title: COMP-2913 React & Modern JavaScript
description: British Columbia Institute of Technology - School of Computing and Academic Studies
author: Daniel K. Takeuchi
github: https://daniel-takeuchi.github.io/COMP-2913
about: For any questions, feedback or concerns, please email me, and I will get back within 48 hours.
disqus_shortname: comp2913
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg
future: false

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/kiyohiko/"

urls:
    - text: Course Outline
      url: /course_outline
    - text: Helpful Resources
      url: /help
    - text: Deliverables
      url: /deliverables
    - text: About
      url: /about
    # - text: My Projects
    #   url: /projects/
    # - text: XML Feed
    #   url: /feed.xml

url: "https://daniel-takeuchi.github.io"
baseurl: "/COMP-2913"
email: "dtakeuchi@my.bcit.ca"
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
